code review
STA-Development/Exp_API pull request #11
Opened 2022-04-18 22:15 UTC by avo2003

2022-04-18 22:18 UTC, ArthurO2002 requested changes
change PR title, do propper commit with propper error message 

like: FIX: resolve comments under pull request

2022-04-18 22:18 UTC, ArthurO2002 commented on src/users/repository/userRepository.ts
>        salary: salary
variable name should be with lowercase

2022-04-18 22:41 UTC, ArthurO2002 approved these changes, later dismissed

2022-04-19 00:55 UTC, harutyunyan611 requested changes

2022-04-19 00:55 UTC, harutyunyan611 commented on src/users/repository/userRepository.ts
> +    return this.userRepository.save(salary);
it's not salary I think

2022-04-19 16:39 UTC, harutyunyan611 approved these changes
LGTM

2022-04-19 16:39 UTC, merged