added evaluator and evaluatee
STA-Development/Exp_API pull request #17
Opened 2022-04-21 15:41 UTC by Zt0

2022-04-22 18:04 UTC, harutyunyan611 requested changes

2022-04-22 18:04 UTC, harutyunyan611 commented on package.json
> +      "prettier": "prettier --config .prettierrc 'src/**/*.ts' --write",
Difference between this two?

2022-04-22 18:04 UTC, harutyunyan611 commented on package.json
> +      "eslint": "eslint --ignore-pattern '.eslintrc.js' --ext .js,.ts ."
Difference between this two?

2022-04-22 18:04 UTC, harutyunyan611 commented on src/events/dto/elementIdDto.ts
> +export class elementIdDto implements IElementIdDto {
What is element

2022-04-29 14:38 UTC, harutyunyan611 submitted a review, later dismissed

2022-05-03 14:39 UTC, ArthurO2002 requested changes

2022-05-03 14:39 UTC, ArthurO2002 commented on src/events/controller/criteriaController.ts
> +  addSubCriteria(
change :id to eventId to be more clear

2022-05-03 14:39 UTC, ArthurO2002 commented on src/events/controller/criteriaController.ts
> +  update(@Param('id') id: number, @Body() updateCriteriaDto: UpdateCriteriaDto): Promise<Criteria> {
use patch

2022-05-03 14:39 UTC, ArthurO2002 commented on src/events/controller/eventController.ts
> +  addRating(@Param('id') eventId: number, @Body() ratingRef: elementIdDto): Promise<Event> {
use patch here too

2022-05-03 14:39 UTC, ArthurO2002 commented on src/events/controller/eventController.ts
> +  @Put(':id/criteria')
.

2022-05-03 14:39 UTC, ArthurO2002 commented on src/events/controller/eventController.ts
> +  @Put(':id/subCriteria')
.

2022-05-03 14:39 UTC, ArthurO2002 commented on src/events/controller/eventController.ts
> +  @Put(':id/evaluator')
.

2022-05-03 14:39 UTC, ArthurO2002 commented on src/events/controller/eventController.ts
> +  @Put(':id/evaluatee')
.

2022-05-03 14:39 UTC, ArthurO2002 commented on src/events/dto/EventEvaluateeGetDto.ts
> +;``
hn?

2022-05-03 14:39 UTC, ArthurO2002 commented on src/events/dto/eventCreateDto.ts
> +  readonly bonus: number
Are you sure this fields are readonly?

2022-05-09 16:05 UTC, harutyunyan611 approved these changes

2022-05-09 16:05 UTC, merged