FEAT: async firebase
STA-Development/Exp_API pull request #8
Opened 2022-04-08 19:50 UTC by avo2003

2022-04-11 19:31 UTC, harutyunyan611 requested changes

2022-04-11 19:31 UTC, harutyunyan611 commented on src/middlewares/checkJwt.ts
> +                res.locals.userUid = decodedIdToken.uid
Spaces

2022-04-11 19:31 UTC, harutyunyan611 commented on src/users/controller/userController.ts
> +     createUserDto.avatar=process.env.AVATAR_URL;
Why in the controller?

2022-04-11 19:31 UTC, harutyunyan611 commented on src/users/controller/userController.ts
> +   findOne(@Token() data: string): Promise<User> {
What is data?

2022-04-11 19:31 UTC, harutyunyan611 commented on src/users/controller/userController.ts
> +  remove(@Param('id') id: number,@Token() data: string): Promise<User> {
Same here

2022-04-11 19:31 UTC, harutyunyan611 commented on src/users/controller/userController.ts
> +   changeUserImg(@UploadedFile() file: Express.Multer.File,@Token() data: string,
Here

2022-04-11 19:31 UTC, harutyunyan611 commented on src/users/controller/userController.ts
> +   changeSalary(
```suggestion
  changeSalary(
```

2022-04-11 19:31 UTC, harutyunyan611 commented on src/users/controller/userController.ts
> +    @Token() data: string,
WHy data?

2022-04-11 19:31 UTC, harutyunyan611 commented on src/users/dto/userCreateDto.ts
> +  authUid: string;
Why optional?

2022-04-11 19:31 UTC, harutyunyan611 commented on src/users/repository/userRepository.ts
> +    return this.userRepository.remove(removeUserId);}
Spacing meseed up

2022-04-11 19:31 UTC, harutyunyan611 commented on src/users/service/userService.ts
>      if (!user) {
What is data?

2022-04-11 20:27 UTC, ArthurO2002 requested changes
@harutyunyan611 to confirm

2022-04-11 20:27 UTC, ArthurO2002 commented on src/users/controller/userController.ts
> +    return this.usersService.remove(id,uid);
fix tabulation on each file

2022-04-11 20:27 UTC, ArthurO2002 commented on src/users/dto/userCreateDto.ts
?????!!!!

2022-04-11 20:27 UTC, ArthurO2002 commented on src/users/dto/userCreateDto.ts
> +}
Why are events readOnly? @Zt0

2022-04-11 20:27 UTC, ArthurO2002 commented on src/users/repository/userRepository.ts
>    }
tabulation

2022-04-11 20:27 UTC, ArthurO2002 commented on src/users/repository/userRepository.ts
>    }
If user will not be admin, they will receive nothing?

2022-04-11 20:27 UTC, ArthurO2002 commented on src/users/service/userService.ts
>      }
Test and attach screenshot, how is it working))))


add await to make this work

2022-04-11 20:27 UTC, ArthurO2002 commented on src/users/controller/userController.ts
> +    return  this.usersService.findOne(uid)
How this will work, if it does not have await

2022-04-11 20:27 UTC, ArthurO2002 commented on src/users/controller/userController.ts
> +    return this.usersService.remove(id,uid);
Without await again?

2022-04-11 20:27 UTC, ArthurO2002 commented on src/users/controller/userController.ts
> +    return  this.usersService.changeSalary(uid,body.salary,id)
fix tabulation

2022-04-11 20:27 UTC, ArthurO2002 commented on src/users/repository/userRepository.ts
>      return user;
unnecessary const

2022-04-11 20:27 UTC, ArthurO2002 commented on src/users/service/userService.ts
> +      throw new NotFoundException(`you have wrong schema`);
what schema, error is not understandable

2022-04-11 20:27 UTC, ArthurO2002 commented on src/users/service/userService.ts
> +      throw new NotFoundException(`you have wrong schema`);
throw ner error with statusCode 405 and with correct error message

2022-04-11 20:27 UTC, ArthurO2002 commented on src/users/service/userService.ts
> +    const user =  this.usersRepository.findOne(authUid);
use await

2022-04-11 20:27 UTC, ArthurO2002 commented on src/users/service/userService.ts
> +    const user =this.usersRepository.remove(id,uid);
fix tabulation

2022-04-11 20:27 UTC, ArthurO2002 commented on src/users/service/userService.ts
>      if(user.isAdmin){
configure eslint and prettier for your webstorm

2022-04-11 20:27 UTC, ArthurO2002 commented on src/users/service/userService.ts
>        await this.cloudinary.deleteImg(userId.avatarPublicId);
tabulation

2022-04-11 22:23 UTC, ArthurO2002 commented on src/users/dto/userCreateDto.ts
why is lastname readonly

2022-04-12 09:55 UTC, avo2003 commented on src/users/controller/userController.ts
> +    return this.usersService.remove(id,uid);
done

2022-04-15 13:05 UTC, harutyunyan611 requested changes

2022-04-15 13:05 UTC, harutyunyan611 commented on src/users/controller/userController.ts
> +    return await this.usersService.findOne(uid);
Why async await

2022-04-15 13:05 UTC, harutyunyan611 commented on src/users/controller/userController.ts
> +    return await this.usersService.remove(id, uid);
Why async await?

2022-04-15 13:05 UTC, harutyunyan611 commented on src/users/dto/userCreateDto.ts
> +  authUid: string;
Then why in DTO? Can we remove it?

2022-04-15 13:05 UTC, harutyunyan611 commented on src/users/dto/userGetDto.ts
> +  authUid: user.authUid,
I think same here, maybe not

2022-04-15 13:05 UTC, harutyunyan611 commented on src/users/repository/userRepository.ts
> +    const user = this.userRepository.create(createUserDto);
Can you check the type of this? If it's promise we should add await

2022-04-15 13:05 UTC, harutyunyan611 commented on src/users/repository/userRepository.ts
> +      relations: ['events'],
Why async await?

2022-04-15 13:05 UTC, harutyunyan611 commented on src/users/repository/userRepository.ts
> +      return await this.userRepository.remove(removeUserId);
Why return await?

2022-04-15 13:05 UTC, harutyunyan611 commented on src/users/repository/userRepository.ts
> +    if (!user) {
Doesn't make sense, we're checking if a user is an admin, and then checking if the user exists. I think logic should be vice versa

2022-04-15 13:05 UTC, harutyunyan611 commented on src/users/service/userService.ts
> +      throw new NotFoundException(`you have wrong schema`);
What is schema?

2022-04-15 13:05 UTC, harutyunyan611 commented on src/users/service/userService.ts
> +      throw new NotFoundException(`you have wrong schema`);
Why not found the error on creating the user?

2022-04-15 13:05 UTC, harutyunyan611 commented on src/users/service/userService.ts
> +    const user = this.usersRepository.update(id, updateUserDto);
Where is async await?

2022-04-15 13:05 UTC, harutyunyan611 commented on src/users/service/userService.ts
> +    return user;
Can we ensure what's returning remove function? Maybe we can wrap it with try catch

2022-04-15 13:05 UTC, harutyunyan611 commented on src/utils/sendEmail.ts
> +      user: process.env.email,
Email camelcase

2022-04-15 13:05 UTC, harutyunyan611 commented on src/utils/sendEmail.ts
>  // const ejs = require ('ejs')
Remove comment

2022-04-15 21:52 UTC, harutyunyan611 approved these changes

2022-04-15 21:52 UTC, merged